name: enarxbot
description: GitHub Actions project automation for Enarx

branding:
  icon: zap
  color: gray-dark

runs:
  using: "composite"
  steps:
    - run: bash -c "env | sort"
      shell: bash
    - run: cat $GITHUB_EVENT_PATH
      shell: bash
    - run: $/enarxbot-pr-triage
      shell: python
