name: enarxbot
description: GitHub Actions project automation for Enarx

branding:
  icon: zap
  color: gray-dark

runs:
  using: "composite"
  steps:
    - run: bash -c "env | sort"
      shell: bash
      env:
        BAR: ${{ secrets.TEST_SECRET }}
