name: enarxbot
description: GitHub Actions project automation for Enarx

branding:
  icon: zap
  color: gray-dark

runs:
  env:
#    TEST_SECRET: ${{ secrets.TEST_SECRET }}
    DUMMY: dummy
  using: "composite"
  steps:
    - run: bash -c "env | sort"
      shell: bash
