name: enarxbot
description: GitHub Actions project automation for Enarx

branding:
  icon: zap
  color: gray-dark

runs:
  using: "composite"
  steps:
    - run: python3 -m pip install -qqq --upgrade pip
      shell: bash
    - run: python3 -m pip install -qqq githubgql
      shell: bash
    - run: echo " --- TRIAGE --- " && $GITHUB_ACTION_PATH/enarxbot-triage
      shell: bash
    - run: echo " --- ASSIGNED --- " && $GITHUB_ACTION_PATH/enarxbot-assigned
      shell: bash
    - run: bash -c "env | sort"
      shell: bash
    - run: cat $GITHUB_EVENT_PATH
      shell: bash
