#!/usr/bin/python3
# SPDX-License-Identifier: Apache-2.0

from github import Github
import enarxbot
import os

github = Github(os.environ['GITHUB_TOKEN'])
org = github.get_organization('enarx')

project = {p.name: p for p in org.get_projects(state='open')}['Sprint']
columns = {c.name: c for c in project.get_columns()}

for issue in github.search_issues(f"org:enarx is:issue state:open is:public -label:conference -project:enarx/{project.number}"):
    if issue.assignee is not None:
        enarxbot.create_card(columns['Assigned'], issue.id, 'Issue')

for issue in github.search_issues(f"org:enarx is:pr state:open is:public -project:enarx/{project.number}"):
    pr = issue.as_pull_request()

    if pr.assignee is not None:
        enarxbot.create_card(columns['Reviewing'], pr.id, 'PullRequest')
