#!/usr/bin/python3
# SPDX-License-Identifier: Apache-2.0

import common

github = common.github()
org = github.get_organization('enarx')

project = {p.name: p for p in org.get_projects(state='open')}['Sprint']
columns = {c.name: c for c in project.get_columns()}

for issue in github.search_issues(f"org:enarx is:issue state:open is:public -label:conference -project:enarx/{project.number}"):
    if issue.assignee is not None:
        columns['Assigned'].create_card(content_id=issue.id, content_type='Issue')

for issue in github.search_issues(f"org:enarx is:pr state:open is:public -project:enarx/{project.number}"):
    pr = issue.as_pull_request()

    if pr.assignee is not None:
        columns['Reviewing'].create_card(content_id=pr.id, content_type='PullRequest')
