#!/usr/bin/python3
# SPDX-License-Identifier: Apache-2.0

from github import Github
import os

github = Github(os.environ['GITHUB_TOKEN'])

for issue in github.search_issues(f"org:enarx state:open is:public is:pr"):
    pr = issue.as_pull_request()

    reviewers = {r.user.login for r in pr.get_reviews() if r.state == 'CHANGES_REQUESTED'}
    requested = {r.login for r in pr.get_review_requests()[0]}
    assignees = {a.login for a in pr.assignees}

    remove = reviewers - requested
    needed = requested | ({pr.user.login} if remove else {})

    remove &= assignees
    needed -= assignees

    pr.remove_from_assignees(*remove)
    pr.add_to_assignees(*needed)
