name: cleanup-sprint-board

on:
  workflow_dispatch

jobs:
  manual:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: post-sprint-cleanup
      run: enarxbot-post-sprint-cleanup
